### ISSUE TITLE
calc_structure

### ISSUE THREAD

**Issue by theScriptingEngineer** [audunarn/ANYstructure#116]
Hello,

I get the following error when running the program (both via the GUI and If I run the code itself with example_data.py):

```
  File "/home/frederik/theScriptingEngineer/Python/ANYstructure/ANYstructure_local/calc_structure.py", line 1895, in stiffened_panel
    stf_pl_data['UF Plate side'] = res_iter_pl.fun[0]
TypeError: 'float' object is not subscriptable
```

Unfortunately I don't understand the code enough to propose a solution...

**Comment by audunarn** [comment]
Hi! I will look into it.

**Comment by audunarn** [comment]
Seem to be an issue with scipy.minimize. Maybe it is updated, don't know. Anyway, I fixed it in the dev and master.
