### ISSUE TITLE
Bending stress in 3.3 unstiffened curved panel / 3.4 unstiffened circular cylinders

### ISSUE THREAD

**Issue by theScriptingEngineer** [audunarn/ANYstructure#127]
Hi Audun,

I think there is a small bug in the code for unstiffened curved.

calc_structure.py:
In the function unstiffened_shell, the sign for the bending stress is set zero or the absolute value depending on the sign (line 2961). This is fine, but changes the value of smsd.

A bit further in the code, '3.4 unstiffened circular cylinders', the same is done for sm0sd (line 3135). However, this uses the value of smsd, which is changed earlier, resulting in the bending stress not correctly being taken into account.

I would suggest moving the calculation of sa0sd, sm0sd to the beginning of the function, only doing it once and used these values in the further calculations.

Hope my explanation is clear.
Regards,
Frederik

**Comment by audunarn** [comment]
Thanks! I will fix this.

**Comment by audunarn** [comment]
Updated as suggested:

        if geometry in [2,6]:
            sxsd = sasd+smsd
        else:
            sxsd = min(sasd, sasd+smsd, sasd-smsd)

        if smsd < 0:
            smsd = -smsd
            sm0sd = -smsd
        else:
            if geometry in [2, 6]:
                smsd = 0
                sm0sd = 0
            else:
                smsd = smsd
                sm0sd = smsd
