### ISSUE TITLE
Clean up code.

### ISSUE THREAD

**Issue by audunarn** [audunarn/ANYstructure#4]
The code is partially a mess. Should be cleaned up.

**Comment by tovop** [comment]
Cool. I'll take a look at it. Some immediate thoughts: should create a package out of it, setup automatic build, testing and deployment using Travis, deploy to pypi.

**Comment by audunarn** [comment]
Hi, thanks for your thoughts. I am still new to that part of development methods but I definitly see the need. Any involvemnt is more than welcome.

**Comment by audunarn** [comment]
No plans to clean up.
