### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by lewiuberg** [audunarn/ANYstructure#49]
Hi!

I see you made plans to shift to Kivy, is this still something you are considering?

**Comment by audunarn** [comment]
Hei!
Nei, det blir nok for mye jobb. Lurer på om jeg skal låse denne.

**Comment by lewiuberg** [comment]
Den er grei! Sitter å jobber litt med Kivy nå. Skal se om det passer til et annet prosjekt jeg driver med.

**Comment by audunarn** [comment]
Om du finner ut hva som skal til for å flytte fra tkinter til kivy så er det interessant.

**Comment by RubendeBruin** [comment]
Just curios but why would you prefer Kivy over Qt?

**Comment by lewiuberg** [comment]
I have no experience with PyQt, or with Kivy. I have dabbled around with Kivy for a couple of hours, and I am not sure it will be the best fit for my other project either. My other project should be able to run on Windows, macOS, Android, and iOS, that is the reason I am looking into it. To me, it seems that if the mobile platforms aren't the goal, find something else. I actually started to read about PyQt yesterday, and it seems like a better fit for this project, or something called wxPython. 

Do you have any input here @RubendeBruin?

**Comment by audunarn** [comment]
I initially planned for some kind om mobile version. So Kivy seemed like a good option. Howver, mobile version is no longer on the agenda. So tkinter is fine.

**Comment by lewiuberg** [comment]
Have you tested it on a mac? It looks very strange on my end, but I have not looked to much into it yet.

**Comment by audunarn** [comment]
No testing on mac. I generally know it can look strange at low resolutions.

**Comment by RubendeBruin** [comment]
@lewiuberg , I'm using Qt myself quite a lot in combination with VTK for the development of [DAVE](https://github.com/RubendeBruin/DAVE). 
A really useful site it https://www.learnpyqt.com/ and the book that you can buy there. 
I prefer PySide over PyQt (just two bindings for Qt) as PySide is the "official" binding.

There is quite a learning curve but I do find myself quite efficient with it now.

**Comment by lewiuberg** [comment]
I had a major system meltdown, so sorry for the late reply. This is how it looks on my Mac.
![Skjermbilde 2021-04-16 kl  21 02 54](https://user-images.githubusercontent.com/43423020/115072135-757a6b80-9ef7-11eb-98b1-77a05366d432.png)

**Comment by audunarn** [comment]
Aiai. That does not look good :) I am not sure what the problem is. The image below is on my computer. 

![image](https://user-images.githubusercontent.com/22213477/115079400-68fb1080-9f01-11eb-8f89-2c082b94c038.png)

**Comment by audunarn** [comment]
Any ideas?

**Comment by lewiuberg** [comment]
I have a calculus assessment due Sunday night, but I can have a look after that :)

**Comment by audunarn** [comment]
Check the self._global_shrink parameter. Try setting it to 1.

**Comment by lewiuberg** [comment]
I have 2560*1440, so no change. However, I was more concerned with the button labels :)

**Comment by audunarn** [comment]
I think mac will not let you change default colors on buttons. Might cause some problems.
