### ISSUE TITLE
Approval / Certification

### ISSUE THREAD

**Issue by RubendeBruin** [audunarn/ANYstructure#64]
I'm asking this question because I'm running into this myself and am wondering if you or anyone else had given it some thought already. 

Some day (soon) people will start using this executable and will be producing reports with it. But how can they be sure that what comes out is correct? Some software packages manage to get an "approved" stamp from some certification authority while others do not.

It would be nice if some sponsor (DNVGL...?) would review the code and give it an approval or a recommendation.

**Comment by audunarn** [comment]
Yes this is an obvious issue. The program should definitly be verified by for example DNVGL or some other classification entity. However, it is hard to see that happen without any commercial interest in the package and without any ability to pay for an approval. Also, DNV have their own kind of (expensive) software that does much of the same as ANYstructure.

As long at it is free and open source people use it at their own risk. But any kind of licensing would require more approval and quality checking of the code and theory. But all software must start somewhere :) 

My best hope, I think, would be to get it approved in some capacity related to a specific project.

What is your plans and thoughts for the future regarding DAVE?

**Comment by audunarn** [comment]
The program has been used in MSA toward DNV. Closing this now. Of course more work is preferrable.
